defaultPortal: career-learning
portals:
  - name: career-learning
    portalId: YOUR_PORTAL_ID
    env: prod
    authType: personalaccesskey
    auth:
      tokenInfo:
        accessToken: YOUR_ACCESS_TOKEN
        expiresAt: '2025-03-07T11:04:32.072Z'
    accountType: STANDARD
    personalAccessKey: YOUR_PERSONAL_ACCESS_KEY

  - name: EmailReportingAccess
    portalId: YOUR_PORTAL_ID
    env: prod
    authType: privateApp
    auth:
      tokenInfo:
        accessToken: YOUR_PRIVATE_APP_TOKEN
        expiresAt: null  # Private app tokens don't expire
      clientId: YOUR_CLIENT_ID
      clientSecret: YOUR_CLIENT_SECRET
      scopes:
        - content
        - marketing
        - crm.objects.contacts.read 